[package]
name = "raytracer"
version = "0.1.0"
authors = ["Aphsai <saksham.a@hotmail.ca>"]
edition = "2018"

[dependencies]
minifb = "0.11.2"
num_cpus = "1.10.1"
threadpool = "1.7.1"
crossbeam = "0.5.0"
